services:
  bdd:
    container_name: gogole-map-bdd
    build: ./bdd
    restart: always
    networks:
      - back
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 15s
      timeout: 5s
      retries: 5

  back:
    container_name: gogole-map-back
    build: ./server
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - front
      - back
    ports:
     - "8080:8080"
    depends_on:
      bdd:
        condition: service_healthy


  front:
    container_name: gogole-map-front
    build: ./client
    networks:
      - front
    ports:
     - "3000:3000"

networks:
  front:
  back: 
